#!/usr/bin/env python3

from argparse import ArgumentParser
import sys
from lisp import evallisp, default_state, loadprelude
import platform

def main(argv):
	parser = ArgumentParser()
	args = parser.parse_args(argv[1:])

	state = loadprelude(default_state)

	print("PyLisp v0.2 - (c) Tuomas Laakkonen 2015.")
	print("Running on %s v%s on %s %s." % (platform.python_implementation(), platform.python_version(),
										  platform.system(), platform.release()))
	print("Prelude loaded. Use (sys.exit) to quit.")

	while True:
		x = [input(">>> ")]
		while True:
			x.append(input('... '))
			if x[-1] == '':
				break
		code = '\n'.join(x)
		result = evallisp(code, state)
		if result is not None:
			print(result)

	return 0

if __name__ == "__main__":
	sys.exit(main(sys.argv))
